### ISSUE TITLE
TF_OLD_DATA error

### ISSUE THREAD

**Issue by huckl3b3rry87** [JuliaMPC/MAVs#68]
demoC
```
Goal sent!
Warning: TF_OLD_DATA ignoring data from the past for frame base_footprintObs at time 0 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.18/src/buffer_core.cpp
[ WARN] [1537754425.280846397, 4.038000000]: Map update loop missed its desired rate of 2.0000Hz... the loop actually took 2.4220 seconds
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 154, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'timeout'
[spawn_obstacles-5] process has finished cleanly
log file: /home/mavs/.ros/log/8e71c3e0-bf9d-11e8-bf8f-fc15b4ebb208/spawn_obstacles-5*.log
[ WARN] [1537754429.706444753, 6.521000000]: Map update loop missed its desired rate of 2.0000Hz... the loop actually took 2.4830 seconds
Warning: TF_OLD_DATA ignoring data from the past for frame base_footprintObs at time 1.2876e+09 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.18/src/buffer_core.cpp
[ WARN] [1537754434.277358481, 9.060000000]: Map update loop missed its desired rate of 2.0000Hz... the loop actually took 2.0390 seconds
Warning: TF_OLD_DATA ignoring data from the past for frame base_footprintObs at time 0 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.18/src/buffer_core.cpp
Warning: TF_OLD_DATA ignoring data from the past for frame base_footprintObs at time 0 according to authority unknown_publisher
Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
         at line 277 in /tmp/binarydeb/ros-kinetic-tf2-0.5.18/src/buffer_core.cpp
[ WARN] [1537754441.016676274, 12.864000000]: Map update loop missed its desired rate of 2.0000Hz... the loop actually took 3.8040 seconds
```

**Comment by huckl3b3rry87** [comment]
@qingjieqi how was this solved?

**Comment by qingjieqi** [comment]
> @qingjieqi how was this solved?

I just figured out the issue #71 was actually referring to #69 instead of this one. I've fixed the typo in #71, and #69 was solved by downloading and using the branch of ruffsl/car_demo https://github.com/ruffsl/car_demo
